name: Release
on:
  push:
    branches: master
jobs:
  push_to_registry:
    name: Build and Push the Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: sqreen/go-dvwa/go-dvwa
          tag_with_ref: true
